version: "3.7"

services:
  bot:
    build: ./src/bot
    restart: always
    env_file: ./.env
    networks:
      - main_net
  web:
    build: ./src/web/
    command: flask run --host=0.0.0.0 --port=5005
    ports:
      - 5005:5005
    restart: always
    env_file: ./.env
    networks:
      - main_net
  db:
    image: postgres:12.0-alpine
    env_file: ./.env
    ports:
      - 5432:5432
    networks:
      - main_net

  nginx:
    image: nginx:latest
    ports:
      - '80:80'
      - '443:443'
    restart: always
    volumes:
      - ./nginx/dev/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
      - ./src/frontend/build:/var/www/html/frontend
      - ./src/web/app/static:/app/static
    networks:
      - main_net




networks:
  main_net:
    external: True
