version: "3.7"

services:
  bot:
    build: ./src/bot
    restart: always
    env_file: ./.env
    networks:
      - main_net
  web:
    build: ./src/web/
    command: flask run --host=0.0.0.0 --port=5005
    ports:
      - 5005:5005
    restart: always
    env_file: ./.env
    networks:
      - main_net
  db:
    image: postgres:12.0-alpine
    env_file: ./.env
    ports:
      - 5432:5432
    networks:
      - main_net

  nginx:
    build: ./nginx/prod
    image: umputun/nginx-le:latest
    hostname: nginx
    restart: always
    container_name: nginx

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

    volumes:
      - ./nginx/prod/etc/ssl:/etc/nginx/ssl
      - ./nginx/prod/etc/service-example.conf:/etc/nginx/service.conf
      - ./src/frontend/build:/var/www/html/frontend
      - ./src/web/app/static:/app/static

    ports:
      - "80:80"
      - "443:443"
    networks:
      - main_net
    env_file:
      - ./.env



networks:
  main_net:
    external: True
